[base]
id = 1
name = "rtthread-smart-qemu"
vm_type = 1
cpu_num = 1
phys_cpu_ids = [0]

[kernel]
entry_point = 0x8008_0000
image_location = "memory"
kernel_path = "path/rtthread-smart-aarch64.bin"
kernel_load_addr = 0x8008_0000
dtb_path = "path/rtthread-smart-aarch64.dtb"
dtb_load_addr = 0x8000_0000

# RTT-Smart's early page tables require RAM at the configured physical address.
memory_regions = [
  [0x8000_0000, 0x1000_0000, 0x7, 0], # 256 MiB, MAP_ALLOC
]

[devices]
interrupt_mode = "emulated"

passthrough_devices = [
  ["/pl011@9000000"],
]

passthrough_addresses = []
excluded_devices = []

emu_devices = [
  ["gppt-gicd", 0x0800_0000, 0x1_0000, 0, 0x21, []],
  ["gppt-gicr", 0x080a_0000, 0x2_0000, 0, 0x20, [1, 0x2_0000, 0]],
]
